name: MacOS/iOS/tvOS build

on: [push, pull_request]

jobs:
  precheks:
    name:    MacOS -> Pre-Checks
    runs-on: macos-15

    steps:
    - name: Clone DiligentCore
      uses: actions/checkout@v4
      with:
        repository: DiligentGraphics/DiligentCore
        path:       DiligentCore

    - name: Clone DiligentTools
      uses: actions/checkout@v4
      with:
        path: DiligentTools

    - name: Format validation
      shell: bash
      working-directory: ${{github.workspace}}/DiligentTools/BuildTools/FormatValidation
      run: ./validate_format_mac.sh


  build:
    needs:   precheks
    runs-on: macos-15

    strategy:
      matrix:
        platform:   ["MacOS", "iOS", "tvOS"]
        build_type: ["Debug", "Release"]

        exclude:
          # Exclude tvOS-Release
          - platform:   "tvOS"
            build_type: "Release"

        include:
          - platform:   "MacOS"
            build_type: "Debug"
            cmake_args: "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON"

          - platform:   "MacOS"
            build_type: "Release"
            # For some reason AVX2 causes invalid instruction exception on CI, so disable it
            cmake_args: "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_CLANG_RELEASE_COMPILE_OPTIONS=\"\""

          - platform:  "iOS"
            cmake_args: "-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON"

          - platform:   "tvOS"
            cmake_args: "-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON"

    name: MacOS -> ${{ matrix.platform }}-${{ matrix.build_type }}

    steps:
    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v8

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v8
      with:
        platform: ${{ matrix.platform }}

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v8
      with:
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v8
      with:
        target: install

    - name: DiligentToolsTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-tools-tests@v8

    - name: HLSL2GLSLConverterTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-hlsl2glsl-converter-test@v8

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: ${{ success() && matrix.build_type == 'Release' && matrix.platform == 'MacOS' }}
      with:
        name: DiligentTools-${{ matrix.platform }}-${{ matrix.build_type }}
        path: ${{env.DILIGENT_INSTALL_DIR}}/bin/DiligentTools
        retention-days: 90
