name: Linux

on: [push, pull_request]

jobs:
  build-gcc-9:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Linux -> x64, GCC 9, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure dependencies
      if: success()
      run: |
        sudo apt-get update && sudo apt-get install build-essential libx11-dev libgl1-mesa-dev

    - name: Configure CMake
      if: success()
      env:
        CC: gcc-9
        CXX: g++-9
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "linux" "${{runner.workspace}}" ${{ matrix.config }} "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2

    - name: DiligentToolsTest
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}/DiligentTools/DiligentTools/Tests/DiligentToolsTest/assets"
        ${{runner.workspace}}/build/DiligentTools/Tests/DiligentToolsTest/DiligentToolsTest


  build-clang-10:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Linux -> x64, Clang 10, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure dependencies
      if: success()
      run: |
        sudo apt-get update && sudo apt-get install build-essential libx11-dev libgl1-mesa-dev

    - name: Configure CMake
      if: success()
      env:
        CC: clang-10
        CXX: clang++-10
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "linux" "${{runner.workspace}}" ${{ matrix.config }} "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2

    - name: DiligentToolsTest
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}/DiligentTools/DiligentTools/Tests/DiligentToolsTest/assets"
        ${{runner.workspace}}/build/DiligentTools/Tests/DiligentToolsTest/DiligentToolsTest
